
// This file has been generated by the GUI designer. Do not modify.
namespace Client
{
	public partial class ConnectDialog
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label titleLabel;

		private global::Gtk.Table connAddressTable;

		private global::Gtk.Entry ipEntry;

		private global::Gtk.Label ipLabel;

		private global::Gtk.Entry portEntry;

		private global::Gtk.Label portLabel;

		private global::Gtk.Button cancelButton;

		private global::Gtk.Button connectButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Client.ConnectDialog
			this.Name = "Client.ConnectDialog";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Client.ConnectDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.titleLabel = new global::Gtk.Label();
			this.titleLabel.Name = "titleLabel";
			this.titleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<big><b>Connect to server</b></big>");
			this.titleLabel.UseMarkup = true;
			this.fixed2.Add(this.titleLabel);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.titleLabel]));
			w2.X = 52;
			w2.Y = 30;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.connAddressTable = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.connAddressTable.Name = "connAddressTable";
			this.connAddressTable.RowSpacing = ((uint)(12));
			this.connAddressTable.ColumnSpacing = ((uint)(12));
			// Container child connAddressTable.Gtk.Table+TableChild
			this.ipEntry = new global::Gtk.Entry();
			this.ipEntry.CanFocus = true;
			this.ipEntry.Name = "ipEntry";
			this.ipEntry.IsEditable = true;
			this.ipEntry.InvisibleChar = '●';
			this.connAddressTable.Add(this.ipEntry);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.connAddressTable[this.ipEntry]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child connAddressTable.Gtk.Table+TableChild
			this.ipLabel = new global::Gtk.Label();
			this.ipLabel.Name = "ipLabel";
			this.ipLabel.LabelProp = global::Mono.Unix.Catalog.GetString("IP");
			this.connAddressTable.Add(this.ipLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.connAddressTable[this.ipLabel]));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child connAddressTable.Gtk.Table+TableChild
			this.portEntry = new global::Gtk.Entry();
			this.portEntry.CanFocus = true;
			this.portEntry.Name = "portEntry";
			this.portEntry.IsEditable = true;
			this.portEntry.InvisibleChar = '●';
			this.connAddressTable.Add(this.portEntry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.connAddressTable[this.portEntry]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child connAddressTable.Gtk.Table+TableChild
			this.portLabel = new global::Gtk.Label();
			this.portLabel.Name = "portLabel";
			this.portLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Port");
			this.connAddressTable.Add(this.portLabel);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.connAddressTable[this.portLabel]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.fixed2.Add(this.connAddressTable);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.connAddressTable]));
			w7.X = 30;
			w7.Y = 106;
			w1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.fixed2]));
			w8.Position = 0;
			// Internal child Client.ConnectDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button();
			this.cancelButton.CanDefault = true;
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.AddActionWidget(this.cancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.cancelButton]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.connectButton = new global::Gtk.Button();
			this.connectButton.CanDefault = true;
			this.connectButton.CanFocus = true;
			this.connectButton.Name = "connectButton";
			this.connectButton.UseUnderline = true;
			this.connectButton.Label = global::Mono.Unix.Catalog.GetString("Connect");
			this.AddActionWidget(this.connectButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.connectButton]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 286;
			this.DefaultHeight = 300;
			this.Show();
			this.cancelButton.Clicked += new global::System.EventHandler(this.OnCancelButtonClicked);
			this.connectButton.Clicked += new global::System.EventHandler(this.OnConnectButtonClicked);
		}
	}
}
