
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label dumpConfigLabel;

	private global::Gtk.Label helpLabel;

	private global::Gtk.Label verboseLabel;

	private global::Gtk.Label debugLabel;

	private global::Gtk.Label dliteDebuggerLabel;

	private global::Gtk.Label seedLabel;

	private global::Gtk.Label abel;

	private global::Gtk.Label checkpointLabel;

	private global::Gtk.Label simRedirLabel;

	private global::Gtk.Label progRedirLabel;

	private global::Gtk.Label niceLabel;

	private global::Gtk.Entry configEntry;

	private global::Gtk.Label configLabel;

	private global::Gtk.Entry dumpEntry;

	private global::Gtk.CheckButton helpCheckbutton;

	private global::Gtk.CheckButton verboseCheckbutton;

	private global::Gtk.CheckButton debugCheckbutton;

	private global::Gtk.CheckButton dliteDebuggerCheckbutton;

	private global::Gtk.CheckButton initAndEndCheckbutton;

	private global::Gtk.Button dumpBrowseButton;

	private global::Gtk.Entry simReditEntry;

	private global::Gtk.Button simRedirBrowseButton;

	private global::Gtk.Button progRedirBrowseButton;

	private global::Gtk.Entry progRedirEntry;

	private global::Gtk.SpinButton schedulingSpinbutton;

	private global::Gtk.SpinButton seedSpinbutton;

	private global::Gtk.SpinButton maxInstSpinbutton;

	private global::Gtk.Label bpredLabel;

	private global::Gtk.ComboBox bpredCombobox;

	private global::Gtk.Button configBrowseButton;

	private global::Gtk.Label maxInstLabel;

	private global::Gtk.Button simulateButton;

	private global::Gtk.Label l1sizeLabel;

	private global::Gtk.SpinButton l1sizeSpinbutton;

	private global::Gtk.Label l2sizeLabel;

	private global::Gtk.SpinButton l2sizeSpinbutton;

	private global::Gtk.Label histSizeLabel;

	private global::Gtk.SpinButton histSizeSpinbutton;

	private global::Gtk.SpinButton xorSpinbutton;

	private global::Gtk.Label xorLabel;

	private global::Gtk.Label titleLabel;

	private global::Gtk.Label metaTableSizeLabel;

	private global::Gtk.Label tableSizeLabel;

	private global::Gtk.SpinButton tableSizeSpinbutton;

	private global::Gtk.SpinButton metaTableSizeSpinbutton;

	private global::Gtk.Label rasSizeLabel;

	private global::Gtk.SpinButton rasSizeSpinbutton;

	private global::Gtk.Label numSetsLabel;

	private global::Gtk.SpinButton numSetsSpinbutton;

	private global::Gtk.SpinButton assocSpinbutton;

	private global::Gtk.Label assocLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dumpConfigLabel = new global::Gtk.Label();
		this.dumpConfigLabel.Name = "dumpConfigLabel";
		this.dumpConfigLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Dump config file");
		this.fixed1.Add(this.dumpConfigLabel);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dumpConfigLabel]));
		w1.X = 27;
		w1.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.helpLabel = new global::Gtk.Label();
		this.helpLabel.Name = "helpLabel";
		this.helpLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Help");
		this.fixed1.Add(this.helpLabel);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.helpLabel]));
		w2.X = 29;
		w2.Y = 186;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.verboseLabel = new global::Gtk.Label();
		this.verboseLabel.Name = "verboseLabel";
		this.verboseLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Verbose");
		this.fixed1.Add(this.verboseLabel);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.verboseLabel]));
		w3.X = 26;
		w3.Y = 239;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.debugLabel = new global::Gtk.Label();
		this.debugLabel.Name = "debugLabel";
		this.debugLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Debug message");
		this.fixed1.Add(this.debugLabel);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.debugLabel]));
		w4.X = 25;
		w4.Y = 287;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dliteDebuggerLabel = new global::Gtk.Label();
		this.dliteDebuggerLabel.Name = "dliteDebuggerLabel";
		this.dliteDebuggerLabel.LabelProp = global::Mono.Unix.Catalog.GetString("DLite Debugger");
		this.fixed1.Add(this.dliteDebuggerLabel);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dliteDebuggerLabel]));
		w5.X = 25;
		w5.Y = 337;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.seedLabel = new global::Gtk.Label();
		this.seedLabel.Name = "seedLabel";
		this.seedLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Seed");
		this.fixed1.Add(this.seedLabel);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.seedLabel]));
		w6.X = 24;
		w6.Y = 387;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.abel = new global::Gtk.Label();
		this.abel.Name = "abel";
		this.abel.LabelProp = global::Mono.Unix.Catalog.GetString("Initialize and terminate immediately");
		this.fixed1.Add(this.abel);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.abel]));
		w7.X = 22;
		w7.Y = 434;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.checkpointLabel = new global::Gtk.Label();
		this.checkpointLabel.Name = "checkpointLabel";
		this.checkpointLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Checkpoint");
		this.fixed1.Add(this.checkpointLabel);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.checkpointLabel]));
		w8.X = 24;
		w8.Y = 478;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.simRedirLabel = new global::Gtk.Label();
		this.simRedirLabel.Name = "simRedirLabel";
		this.simRedirLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Simout save location");
		this.fixed1.Add(this.simRedirLabel);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.simRedirLabel]));
		w9.X = 23;
		w9.Y = 525;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progRedirLabel = new global::Gtk.Label();
		this.progRedirLabel.Name = "progRedirLabel";
		this.progRedirLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Progout save location");
		this.fixed1.Add(this.progRedirLabel);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.progRedirLabel]));
		w10.X = 26;
		w10.Y = 570;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.niceLabel = new global::Gtk.Label();
		this.niceLabel.Name = "niceLabel";
		this.niceLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Simulator scheduling priority");
		this.fixed1.Add(this.niceLabel);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.niceLabel]));
		w11.X = 26;
		w11.Y = 612;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.configEntry = new global::Gtk.Entry();
		this.configEntry.CanFocus = true;
		this.configEntry.Name = "configEntry";
		this.configEntry.IsEditable = true;
		this.configEntry.InvisibleChar = '●';
		this.fixed1.Add(this.configEntry);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.configEntry]));
		w12.X = 137;
		w12.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.configLabel = new global::Gtk.Label();
		this.configLabel.Name = "configLabel";
		this.configLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Config file");
		this.fixed1.Add(this.configLabel);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.configLabel]));
		w13.X = 35;
		w13.Y = 79;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dumpEntry = new global::Gtk.Entry();
		this.dumpEntry.CanFocus = true;
		this.dumpEntry.Name = "dumpEntry";
		this.dumpEntry.IsEditable = true;
		this.dumpEntry.InvisibleChar = '●';
		this.fixed1.Add(this.dumpEntry);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dumpEntry]));
		w14.X = 174;
		w14.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.helpCheckbutton = new global::Gtk.CheckButton();
		this.helpCheckbutton.CanFocus = true;
		this.helpCheckbutton.Name = "helpCheckbutton";
		this.helpCheckbutton.Label = global::Mono.Unix.Catalog.GetString("help");
		this.helpCheckbutton.DrawIndicator = true;
		this.helpCheckbutton.UseUnderline = true;
		this.fixed1.Add(this.helpCheckbutton);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.helpCheckbutton]));
		w15.X = 83;
		w15.Y = 184;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.verboseCheckbutton = new global::Gtk.CheckButton();
		this.verboseCheckbutton.CanFocus = true;
		this.verboseCheckbutton.Name = "verboseCheckbutton";
		this.verboseCheckbutton.Label = global::Mono.Unix.Catalog.GetString("verbose");
		this.verboseCheckbutton.DrawIndicator = true;
		this.verboseCheckbutton.UseUnderline = true;
		this.fixed1.Add(this.verboseCheckbutton);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.verboseCheckbutton]));
		w16.X = 101;
		w16.Y = 238;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.debugCheckbutton = new global::Gtk.CheckButton();
		this.debugCheckbutton.CanFocus = true;
		this.debugCheckbutton.Name = "debugCheckbutton";
		this.debugCheckbutton.Label = global::Mono.Unix.Catalog.GetString("debug");
		this.debugCheckbutton.DrawIndicator = true;
		this.debugCheckbutton.UseUnderline = true;
		this.fixed1.Add(this.debugCheckbutton);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.debugCheckbutton]));
		w17.X = 166;
		w17.Y = 289;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dliteDebuggerCheckbutton = new global::Gtk.CheckButton();
		this.dliteDebuggerCheckbutton.CanFocus = true;
		this.dliteDebuggerCheckbutton.Name = "dliteDebuggerCheckbutton";
		this.dliteDebuggerCheckbutton.Label = global::Mono.Unix.Catalog.GetString("dlite");
		this.dliteDebuggerCheckbutton.DrawIndicator = true;
		this.dliteDebuggerCheckbutton.UseUnderline = true;
		this.fixed1.Add(this.dliteDebuggerCheckbutton);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dliteDebuggerCheckbutton]));
		w18.X = 161;
		w18.Y = 337;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.initAndEndCheckbutton = new global::Gtk.CheckButton();
		this.initAndEndCheckbutton.CanFocus = true;
		this.initAndEndCheckbutton.Name = "initAndEndCheckbutton";
		this.initAndEndCheckbutton.Label = global::Mono.Unix.Catalog.GetString("init/end");
		this.initAndEndCheckbutton.DrawIndicator = true;
		this.initAndEndCheckbutton.UseUnderline = true;
		this.fixed1.Add(this.initAndEndCheckbutton);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.initAndEndCheckbutton]));
		w19.X = 326;
		w19.Y = 432;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.dumpBrowseButton = new global::Gtk.Button();
		this.dumpBrowseButton.CanFocus = true;
		this.dumpBrowseButton.Name = "dumpBrowseButton";
		this.dumpBrowseButton.UseUnderline = true;
		this.dumpBrowseButton.Label = global::Mono.Unix.Catalog.GetString("Browse");
		this.fixed1.Add(this.dumpBrowseButton);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.dumpBrowseButton]));
		w20.X = 350;
		w20.Y = 132;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.simReditEntry = new global::Gtk.Entry();
		this.simReditEntry.CanFocus = true;
		this.simReditEntry.Name = "simReditEntry";
		this.simReditEntry.IsEditable = true;
		this.simReditEntry.InvisibleChar = '●';
		this.fixed1.Add(this.simReditEntry);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.simReditEntry]));
		w21.X = 197;
		w21.Y = 519;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.simRedirBrowseButton = new global::Gtk.Button();
		this.simRedirBrowseButton.CanFocus = true;
		this.simRedirBrowseButton.Name = "simRedirBrowseButton";
		this.simRedirBrowseButton.UseUnderline = true;
		this.simRedirBrowseButton.Label = global::Mono.Unix.Catalog.GetString("Browse");
		this.fixed1.Add(this.simRedirBrowseButton);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.simRedirBrowseButton]));
		w22.X = 373;
		w22.Y = 518;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progRedirBrowseButton = new global::Gtk.Button();
		this.progRedirBrowseButton.CanFocus = true;
		this.progRedirBrowseButton.Name = "progRedirBrowseButton";
		this.progRedirBrowseButton.UseUnderline = true;
		this.progRedirBrowseButton.Label = global::Mono.Unix.Catalog.GetString("Browse");
		this.fixed1.Add(this.progRedirBrowseButton);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.progRedirBrowseButton]));
		w23.X = 385;
		w23.Y = 565;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.progRedirEntry = new global::Gtk.Entry();
		this.progRedirEntry.CanFocus = true;
		this.progRedirEntry.Name = "progRedirEntry";
		this.progRedirEntry.IsEditable = true;
		this.progRedirEntry.InvisibleChar = '●';
		this.fixed1.Add(this.progRedirEntry);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.progRedirEntry]));
		w24.X = 209;
		w24.Y = 564;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.schedulingSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.schedulingSpinbutton.CanFocus = true;
		this.schedulingSpinbutton.Name = "schedulingSpinbutton";
		this.schedulingSpinbutton.Adjustment.PageIncrement = 10D;
		this.schedulingSpinbutton.ClimbRate = 1D;
		this.schedulingSpinbutton.Numeric = true;
		this.fixed1.Add(this.schedulingSpinbutton);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.schedulingSpinbutton]));
		w25.X = 274;
		w25.Y = 609;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.seedSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.seedSpinbutton.CanFocus = true;
		this.seedSpinbutton.Name = "seedSpinbutton";
		this.seedSpinbutton.Adjustment.PageIncrement = 10D;
		this.seedSpinbutton.ClimbRate = 1D;
		this.seedSpinbutton.Numeric = true;
		this.fixed1.Add(this.seedSpinbutton);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.seedSpinbutton]));
		w26.X = 74;
		w26.Y = 381;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.maxInstSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.maxInstSpinbutton.CanFocus = true;
		this.maxInstSpinbutton.Name = "maxInstSpinbutton";
		this.maxInstSpinbutton.Adjustment.PageIncrement = 10D;
		this.maxInstSpinbutton.ClimbRate = 1D;
		this.maxInstSpinbutton.Numeric = true;
		this.fixed1.Add(this.maxInstSpinbutton);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.maxInstSpinbutton]));
		w27.X = 265;
		w27.Y = 657;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bpredLabel = new global::Gtk.Label();
		this.bpredLabel.Name = "bpredLabel";
		this.bpredLabel.LabelProp = global::Mono.Unix.Catalog.GetString("bpred");
		this.fixed1.Add(this.bpredLabel);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.bpredLabel]));
		w28.X = 525;
		w28.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bpredCombobox = global::Gtk.ComboBox.NewText();
		this.bpredCombobox.AppendText(global::Mono.Unix.Catalog.GetString("nottaken"));
		this.bpredCombobox.AppendText(global::Mono.Unix.Catalog.GetString("taken"));
		this.bpredCombobox.AppendText(global::Mono.Unix.Catalog.GetString("bimod"));
		this.bpredCombobox.AppendText(global::Mono.Unix.Catalog.GetString("2lev"));
		this.bpredCombobox.AppendText(global::Mono.Unix.Catalog.GetString("comb"));
		this.bpredCombobox.Name = "bpredCombobox";
		this.bpredCombobox.Active = 2;
		this.fixed1.Add(this.bpredCombobox);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.bpredCombobox]));
		w29.X = 579;
		w29.Y = 68;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.configBrowseButton = new global::Gtk.Button();
		this.configBrowseButton.CanDefault = true;
		this.configBrowseButton.CanFocus = true;
		this.configBrowseButton.Name = "configBrowseButton";
		this.configBrowseButton.UseUnderline = true;
		this.configBrowseButton.Label = global::Mono.Unix.Catalog.GetString("Browse");
		this.fixed1.Add(this.configBrowseButton);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.configBrowseButton]));
		w30.X = 315;
		w30.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.maxInstLabel = new global::Gtk.Label();
		this.maxInstLabel.Name = "maxInstLabel";
		this.maxInstLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Max instructions to execute");
		this.fixed1.Add(this.maxInstLabel);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.maxInstLabel]));
		w31.X = 27;
		w31.Y = 662;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.simulateButton = new global::Gtk.Button();
		this.simulateButton.CanFocus = true;
		this.simulateButton.Name = "simulateButton";
		this.simulateButton.UseUnderline = true;
		this.simulateButton.Label = global::Mono.Unix.Catalog.GetString("Simulate");
		this.fixed1.Add(this.simulateButton);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.simulateButton]));
		w32.X = 1289;
		w32.Y = 649;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l1sizeLabel = new global::Gtk.Label();
		this.l1sizeLabel.Name = "l1sizeLabel";
		this.l1sizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("l1size");
		this.fixed1.Add(this.l1sizeLabel);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l1sizeLabel]));
		w33.X = 793;
		w33.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l1sizeSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.l1sizeSpinbutton.CanFocus = true;
		this.l1sizeSpinbutton.Name = "l1sizeSpinbutton";
		this.l1sizeSpinbutton.Adjustment.PageIncrement = 10D;
		this.l1sizeSpinbutton.ClimbRate = 1D;
		this.l1sizeSpinbutton.Numeric = true;
		this.fixed1.Add(this.l1sizeSpinbutton);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l1sizeSpinbutton]));
		w34.X = 854;
		w34.Y = 69;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l2sizeLabel = new global::Gtk.Label();
		this.l2sizeLabel.Name = "l2sizeLabel";
		this.l2sizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("l2size");
		this.fixed1.Add(this.l2sizeLabel);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l2sizeLabel]));
		w35.X = 793;
		w35.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.l2sizeSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.l2sizeSpinbutton.CanFocus = true;
		this.l2sizeSpinbutton.Name = "l2sizeSpinbutton";
		this.l2sizeSpinbutton.Adjustment.PageIncrement = 10D;
		this.l2sizeSpinbutton.ClimbRate = 1D;
		this.l2sizeSpinbutton.Numeric = true;
		this.fixed1.Add(this.l2sizeSpinbutton);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.l2sizeSpinbutton]));
		w36.X = 854;
		w36.Y = 130;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.histSizeLabel = new global::Gtk.Label();
		this.histSizeLabel.Name = "histSizeLabel";
		this.histSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("histSize");
		this.fixed1.Add(this.histSizeLabel);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.histSizeLabel]));
		w37.X = 985;
		w37.Y = 76;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.histSizeSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.histSizeSpinbutton.CanFocus = true;
		this.histSizeSpinbutton.Name = "histSizeSpinbutton";
		this.histSizeSpinbutton.Adjustment.PageIncrement = 10D;
		this.histSizeSpinbutton.ClimbRate = 1D;
		this.histSizeSpinbutton.Numeric = true;
		this.fixed1.Add(this.histSizeSpinbutton);
		global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.histSizeSpinbutton]));
		w38.X = 1070;
		w38.Y = 71;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.xorSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.xorSpinbutton.CanFocus = true;
		this.xorSpinbutton.Name = "xorSpinbutton";
		this.xorSpinbutton.Adjustment.PageIncrement = 10D;
		this.xorSpinbutton.ClimbRate = 1D;
		this.xorSpinbutton.Numeric = true;
		this.fixed1.Add(this.xorSpinbutton);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.xorSpinbutton]));
		w39.X = 1071;
		w39.Y = 126;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.xorLabel = new global::Gtk.Label();
		this.xorLabel.Name = "xorLabel";
		this.xorLabel.LabelProp = global::Mono.Unix.Catalog.GetString("xor");
		this.fixed1.Add(this.xorLabel);
		global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.xorLabel]));
		w40.X = 1023;
		w40.Y = 133;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.titleLabel = new global::Gtk.Label();
		this.titleLabel.Name = "titleLabel";
		this.titleLabel.Xpad = 485;
		this.titleLabel.Ypad = 4;
		this.titleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Branch prediction simulator");
		this.fixed1.Add(this.titleLabel);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.titleLabel]));
		w41.X = 74;
		w41.Y = 17;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.metaTableSizeLabel = new global::Gtk.Label();
		this.metaTableSizeLabel.Name = "metaTableSizeLabel";
		this.metaTableSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("MetaTableSize");
		this.fixed1.Add(this.metaTableSizeLabel);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.metaTableSizeLabel]));
		w42.X = 730;
		w42.Y = 268;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tableSizeLabel = new global::Gtk.Label();
		this.tableSizeLabel.Name = "tableSizeLabel";
		this.tableSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("TableSize");
		this.fixed1.Add(this.tableSizeLabel);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tableSizeLabel]));
		w43.X = 768;
		w43.Y = 202;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.tableSizeSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.tableSizeSpinbutton.CanFocus = true;
		this.tableSizeSpinbutton.Name = "tableSizeSpinbutton";
		this.tableSizeSpinbutton.Adjustment.PageIncrement = 10D;
		this.tableSizeSpinbutton.ClimbRate = 1D;
		this.tableSizeSpinbutton.Numeric = true;
		this.fixed1.Add(this.tableSizeSpinbutton);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tableSizeSpinbutton]));
		w44.X = 860;
		w44.Y = 197;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.metaTableSizeSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.metaTableSizeSpinbutton.CanFocus = true;
		this.metaTableSizeSpinbutton.Name = "metaTableSizeSpinbutton";
		this.metaTableSizeSpinbutton.Adjustment.PageIncrement = 10D;
		this.metaTableSizeSpinbutton.ClimbRate = 1D;
		this.metaTableSizeSpinbutton.Numeric = true;
		this.fixed1.Add(this.metaTableSizeSpinbutton);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.metaTableSizeSpinbutton]));
		w45.X = 860;
		w45.Y = 254;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rasSizeLabel = new global::Gtk.Label();
		this.rasSizeLabel.Name = "rasSizeLabel";
		this.rasSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("rasSize");
		this.fixed1.Add(this.rasSizeLabel);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.rasSizeLabel]));
		w46.X = 788;
		w46.Y = 319;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.rasSizeSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.rasSizeSpinbutton.CanFocus = true;
		this.rasSizeSpinbutton.Name = "rasSizeSpinbutton";
		this.rasSizeSpinbutton.Adjustment.PageIncrement = 10D;
		this.rasSizeSpinbutton.ClimbRate = 1D;
		this.rasSizeSpinbutton.Numeric = true;
		this.fixed1.Add(this.rasSizeSpinbutton);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.rasSizeSpinbutton]));
		w47.X = 860;
		w47.Y = 310;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numSetsLabel = new global::Gtk.Label();
		this.numSetsLabel.Name = "numSetsLabel";
		this.numSetsLabel.LabelProp = global::Mono.Unix.Catalog.GetString("numSets");
		this.fixed1.Add(this.numSetsLabel);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.numSetsLabel]));
		w48.X = 778;
		w48.Y = 369;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numSetsSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.numSetsSpinbutton.CanFocus = true;
		this.numSetsSpinbutton.Name = "numSetsSpinbutton";
		this.numSetsSpinbutton.Adjustment.PageIncrement = 10D;
		this.numSetsSpinbutton.ClimbRate = 1D;
		this.numSetsSpinbutton.Numeric = true;
		this.fixed1.Add(this.numSetsSpinbutton);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.numSetsSpinbutton]));
		w49.X = 861;
		w49.Y = 362;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.assocSpinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.assocSpinbutton.CanFocus = true;
		this.assocSpinbutton.Name = "assocSpinbutton";
		this.assocSpinbutton.Adjustment.PageIncrement = 10D;
		this.assocSpinbutton.ClimbRate = 1D;
		this.assocSpinbutton.Numeric = true;
		this.fixed1.Add(this.assocSpinbutton);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.assocSpinbutton]));
		w50.X = 1072;
		w50.Y = 363;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.assocLabel = new global::Gtk.Label();
		this.assocLabel.Name = "assocLabel";
		this.assocLabel.LabelProp = global::Mono.Unix.Catalog.GetString("assoc");
		this.fixed1.Add(this.assocLabel);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.assocLabel]));
		w51.X = 1012;
		w51.Y = 370;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1412;
		this.DefaultHeight = 711;
		this.l1sizeLabel.Hide();
		this.l1sizeSpinbutton.Hide();
		this.l2sizeLabel.Hide();
		this.l2sizeSpinbutton.Hide();
		this.histSizeLabel.Hide();
		this.histSizeSpinbutton.Hide();
		this.xorSpinbutton.Hide();
		this.xorLabel.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.bpredCombobox.Changed += new global::System.EventHandler(this.OnBpredComboboxChanged);
	}
}
